# 🐍 Python Essentials for Agentic AI (2-Hour Crash Course)
This notebook covers the **must-know Python concepts** needed to start working with **Agentic AI**. Each section has explanations and examples.

## 1. Python Basics
Variables, data types, operators, and conditionals form the foundation of all Python programs.

In [2]:
# Variables and Data Types
name = "Agent"
score = 95
active = True

print(name ,type(name), score,type(score), active,type(active))

Agent <class 'str'> 95 <class 'int'> True <class 'bool'>


In [3]:
# Operators and Expressions
result = (score / 10) + 2
print("Result:", result)

# Conditionals
if score > 90:
    print("Excellent Agent!")
else:
    print("Keep training.")

Result: 11.5
Excellent Agent!


## 2. Functions
Functions help organize reusable code.

In [4]:
def greet(agent_name):
    return f"Hello, {agent_name}"

print(greet("AI-007"))

Hello, AI-007


In [5]:
# Function with default argument
def analyze(data, verbose=True):
    if verbose:
        print("Analyzing:", data)
    return len(data)

analyze([1,2,3])

Analyzing: [1, 2, 3]


3

## 3. Data Structures
Lists, dictionaries, and list comprehensions are crucial for handling agent configs, tasks, and results.

In [6]:
# Lists
tasks = ["fetch data", "clean data", "train model"]
print(tasks[0])
tasks.append("deploy")
print(tasks)

fetch data
['fetch data', 'clean data', 'train model', 'deploy']


In [7]:
# Dictionaries
agent = {"name": "PromoGenie", "status": "active"}
print(agent["name"])

# List Comprehension
squares = [x**2 for x in range(5)]
print(squares)

PromoGenie
[0, 1, 4, 9, 16]


## 4. Classes & Objects
Classes are useful for defining **Agent blueprints**.

In [8]:
class Agent:
    def __init__(self, name, role):
        self.name = name
        self.role = role
    
    def act(self, task):
        return f"{self.name} is performing {task}"

a1 = Agent("PromoGenie", "Pricing")
print(a1.act("discount analysis"))

PromoGenie is performing discount analysis


## 5. Modules & Imports
Python has built-in modules and you can also create your own.

In [11]:
import random
print(random.choice(["approve", "reject"]))

reject


## 6. File & JSON Handling
Agents often read/write logs and configs in JSON.

In [12]:
# Writing to a file
with open("log.txt", "w") as f:
    f.write("Agent started\n")

# Working with JSON
import json
config = {"agent": "PromoGenie", "tasks": ["forecast", "pricing"]}
with open("config.json", "w") as f:
    json.dump(config, f)
print("Config written.")

Config written.


## 7. API Calls
Agents interact with external systems using APIs.

In [13]:
import requests
response = requests.get("https://api.github.com")
print(response.json()["current_user_url"])

https://api.github.com/user


## 8. Async & Parallelism
Async allows agents to handle multiple tasks simultaneously.

In [14]:
import asyncio

async def task(n):
    print(f"Task {n} started")
    await asyncio.sleep(1)
    print(f"Task {n} done")

asyncio.run(task(1))

RuntimeError: asyncio.run() cannot be called from a running event loop

## 9. Error Handling
Agents must gracefully recover from errors.

In [15]:
try:
    x = 1 / 0
except ZeroDivisionError as e:
    print("Error:", e)

Error: division by zero


## 10. Mini Agent Simulation
Putting it all together.

In [16]:
import json, random

class Agent:
    def __init__(self, name):
        self.name = name
    
    def decide(self, input_text):
        actions = ["analyze", "respond", "escalate"]
        return random.choice(actions)

# Load config
config = {"agent": "SupportBot"}
a = Agent(config["agent"])
print(a.decide("customer complaint"))

analyze


In [4]:
import os
print(os.getcwd())

d:\react_projects\PyIpynb


In [16]:
with open('example.txt','r') as file:
    content=file.read()
    print(content)

This is my First File Handling
This is an Appended Data
First_one
Second_one
Third_one



In [13]:
with open('example.txt','w') as file:
    file.write('This is my First File Handling\n')

In [14]:
with open('example.txt','a') as file:
    file.write('This is an Appended Data\n')

In [15]:
lines=['First_one\n','Second_one\n','Third_one\n']
with open('example.txt','a') as file:
     file.writelines(lines)

In [17]:
import os
cwd=os.getcwd()
print(f"Current Directory is {cwd}")

Current Directory is d:\react_projects\PyIpynb


In [18]:
new_directory="package"
os.mkdir(new_directory)
print(f"Directory'{new_directory}'create")

Directory'package'create


In [19]:
items=os.listdir('.')
print(items)

['.git', 'config.json', 'example.txt', 'log.txt', 'package', 'Python_Essentials_AgenticAI.ipynb']


In [20]:
dir_name="folder"
file_name="file.txt"
full_path=os.path.join(os.getcwd(),dir_name,file_name)
print(full_path)

d:\react_projects\PyIpynb\folder\file.txt


In [21]:
path='example1.txt'
if os.path.exists(path):
    print(f"The path '{path}' exists")
else:
    print(f"The path '{path}' doesn't exists")

The path 'example1.txt' doesn't exists


In [22]:
import os 

path='example.txt'

if os.path.isfile(path):
    print(f"The path '{path}' is a file.")
elif os.path.isdir(path):
    print(f"The path '{path}' is a directory.")
else:
    print(f"The path '{path}' is neither a file nor a directory.")

The path 'example.txt' is a file.


In [27]:
num = int(input("Enter Numerator: "))
den = int(input("Enter Denominator: "))

try:
    result = num / den
except ZeroDivisionError as ex:
    print("Error:", ex)
else:
    print("Division successful! Result:", result)
finally:
    print("Execution completed.")


Error: division by zero
Execution completed.


In [ ]:
try:
    file=open('example1.txt','r')
    content=file.read()
    a=b
    print(content)
except FileNotFoundError:
    print("The file does not exists")
except Exception as ex:
    print(ex)
finally:
    if 'file' in locals() or not file.closed():
        file.close()
        print('File Close')

The file does not exists


NameError: name 'file' is not defined

In [5]:
class Account:
    def __init__(self,owner,balance):
        self.owner=owner
        self.balance=balance
    def deposit(self,amount):
        self.balance+=amount
        print(f"{amount} is deposited. New Balance is {self.balance}")
    def withdraw(self,amount):
        if amount>self.balance:
            print("Insufficient funds!")
        else:
            self.balance-=amount
            print(f"{amount} is withdrawn. New Balance is {self.balance}")
    def get_balance(self):
        return self.balance
    
## Create an Account
account= Account("Gokul",5000)
print(account.balance)
account.deposit(int(input("Enter Amount:")))
account.withdraw(int(input("Enter Amount:")))

5000
3000 is deposited. New Balance is 8000
3000 is deposited. New Balance is 8000
250 is withdrawn. New Balance is 7750


In [10]:
class Animal:
    def __init__(self,name):
        self.name=name
   
    def speak(self):
        print("Subclass must implement this method")
class Pet:
    def __init__(self,owner):
        self.owner=owner
    
class Dog(Animal, Pet):
    def __init__(self, name, owner):
        super().__init__(name)  # Initializes Animal
        Pet.__init__(self, owner)  # Initializes Pet

    def speak(self):
        return f"{self.name} say woof"

dog = Dog("Buddy", "Gopal")
print(dog.speak())
print(f"Owner of {dog.name} is {dog.owner}")

Buddy say woof
Owner of Buddy is Gopal


In [ ]:
import numpy as np

# Basic: Creating arrays
arr = np.array([1, 2, 3, 4])
print("Basic Array:", arr)

# Array properties
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

# Advanced: Multi-dimensional arrays
matrix = np.array([[1, 2], [3, 4]])
print("2D Array:\n", matrix)

# Array operations
sum_arr = arr + 10
print("Add 10 to each element:", sum_arr)

# Broadcasting
broadcasted = matrix + arr[:2]
print("Broadcasted addition:\n", broadcasted)

# Slicing and indexing
print("First row:", matrix[0])
print("Element at (1,1):", matrix[1,1])

# Advanced: Mathematical functions
sin_arr = np.sin(arr)
print("Sine of array:", sin_arr)

# Advanced: Aggregations
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))

# Advanced: Linear algebra
identity = np.eye(2)
product = np.dot(matrix, identity)
print("Matrix dot identity:\n", product)

# Advanced: Random numbers
rand_nums = np.random.rand(3,2)
print("Random numbers:\n", rand_nums)

# Explanation:
# - np.array creates arrays.
# - Arrays have shape and dtype properties.
# - Operations (+, -, *, /) are element-wise.
# - Broadcasting allows operations on arrays of different shapes.
# - Slicing/indexing works like lists but for any dimension.
# - Mathematical functions (sin, mean, std) work on arrays.
# - np.dot performs matrix multiplication.
# - np.random.rand generates random arrays.

In [1]:
import numpy as np

# Basic: Creating arrays
arr = np.array([1, 2, 3, 4])
print("Basic Array:", arr)


Basic Array: [1 2 3 4]


In [2]:
import numpy as np

# Basic: Creating arrays
arr = np.array([1, 2, 3, 4])
print("Basic Array:", arr)

# Array properties
print("Shape:", arr.shape)
print("Data type:", arr.dtype)

# Advanced: Multi-dimensional arrays
matrix = np.array([[1, 2], [3, 4]])
print("2D Array:\n", matrix)

# Array operations
sum_arr = arr + 10
print("Add 10 to each element:", sum_arr)

# Broadcasting
broadcasted = matrix + arr[:2]
print("Broadcasted addition:\n", broadcasted)

# Slicing and indexing
print("First row:", matrix[0])
print("Element at (1,1):", matrix[1,1])

# Advanced: Mathematical functions
sin_arr = np.sin(arr)
print("Sine of array:", sin_arr)

# Advanced: Aggregations
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))

# Advanced: Linear algebra
identity = np.eye(2)
product = np.dot(matrix, identity)
print("Matrix dot identity:\n", product)

# Advanced: Random numbers
rand_nums = np.random.rand(3,2)
print("Random numbers:\n", rand_nums)

# Explanation:
# - np.array creates arrays.
# - Arrays have shape and dtype properties.
# - Operations (+, -, *, /) are element-wise.
# - Broadcasting allows operations on arrays of different shapes.
# - Slicing/indexing works like lists but for any dimension.
# - Mathematical functions (sin, mean, std) work on arrays.
# - np.dot performs matrix multiplication.
# - np.random.rand generates random arrays.

Basic Array: [1 2 3 4]
Shape: (4,)
Data type: int32
2D Array:
 [[1 2]
 [3 4]]
Add 10 to each element: [11 12 13 14]
Broadcasted addition:
 [[2 4]
 [4 6]]
First row: [1 2]
Element at (1,1): 4
Sine of array: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Mean: 2.5
Standard deviation: 1.118033988749895
Matrix dot identity:
 [[1. 2.]
 [3. 4.]]
Random numbers:
 [[0.12613483 0.83240007]
 [0.00113846 0.15834225]
 [0.51797991 0.77078701]]


In [3]:
import pandas as pd

# Basic: Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85, 90, 95]
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# Accessing columns and rows
print("Names:", df['Name'])
print("First row:\n", df.iloc[0])

# Filtering data
filtered = df[df['Age'] > 28]
print("Filtered (Age > 28):\n", filtered)

# Adding new columns
df['Passed'] = df['Score'] > 90
print("With Passed column:\n", df)

# Aggregations
print("Mean Age:", df['Age'].mean())
print("Max Score:", df['Score'].max())

# GroupBy
grouped = df.groupby('Passed')['Score'].mean()
print("Mean Score by Passed:\n", grouped)

# Handling missing data
df.loc[1, 'Score'] = None
print("With missing value:\n", df)
print("Fill missing Score:\n", df['Score'].fillna(df['Score'].mean()))

# Advanced: Reading/writing CSV
df.to_csv('sample.csv', index=False)
loaded = pd.read_csv('sample.csv')
print("Loaded from CSV:\n", loaded)

# Advanced: Merging DataFrames
df2 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Country': ['USA', 'UK']})
merged = pd.merge(df, df2, on='Name', how='left')
print("Merged DataFrame:\n", merged)

# Advanced: Pivot table
pivot = pd.pivot_table(df, values='Score', index='Passed', aggfunc='mean')
print("Pivot Table:\n", pivot)

DataFrame:
       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
Names: 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
First row:
 Name     Alice
Age         25
Score       85
Name: 0, dtype: object
Filtered (Age > 28):
       Name  Age  Score
1      Bob   30     90
2  Charlie   35     95
With Passed column:
       Name  Age  Score  Passed
0    Alice   25     85   False
1      Bob   30     90   False
2  Charlie   35     95    True
Mean Age: 30.0
Max Score: 95
Mean Score by Passed:
 Passed
False    87.5
True     95.0
Name: Score, dtype: float64
With missing value:
       Name  Age  Score  Passed
0    Alice   25   85.0   False
1      Bob   30    NaN   False
2  Charlie   35   95.0    True
Fill missing Score:
 0    85.0
1    90.0
2    95.0
Name: Score, dtype: float64
Loaded from CSV:
       Name  Age  Score  Passed
0    Alice   25   85.0   False
1      Bob   30    NaN   False
2  Charlie   35   95.0    True
Merged DataFrame:
       Na

In [4]:
import pandas as pd

# Basic: Creating a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85, 90, 95]
}

In [5]:
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95


In [6]:
# Accessing columns and rows
print("Names:", df['Name'])
print("First row:\n", df.iloc[0])

Names: 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
First row:
 Name     Alice
Age         25
Score       85
Name: 0, dtype: object


In [7]:
# Filtering data
filtered = df[df['Age'] > 28]
print("Filtered (Age > 28):\n", filtered)

Filtered (Age > 28):
       Name  Age  Score
1      Bob   30     90
2  Charlie   35     95


In [10]:
# Adding new columns
df['Passed'] = df['Score'] > 90
print("With Passed column:\n", df)

# Aggregations
print("Mean Age:", df['Age'].mean())
print("Max Score:", df['Score'].max())

With Passed column:
       Name  Age  Score  Passed
0    Alice   25     85   False
1      Bob   30     90   False
2  Charlie   35     95    True
Mean Age: 30.0
Max Score: 95


In [11]:
# GroupBy
grouped = df.groupby('Passed')['Score'].mean()
print("Mean Score by Passed:\n", grouped)

# Handling missing data
df.loc[1, 'Score'] = None
print("With missing value:\n", df)
print("Fill missing Score:\n", df['Score'].fillna(df['Score'].mean()))

Mean Score by Passed:
 Passed
False    87.5
True     95.0
Name: Score, dtype: float64
With missing value:
       Name  Age  Score  Passed
0    Alice   25   85.0   False
1      Bob   30    NaN   False
2  Charlie   35   95.0    True
Fill missing Score:
 0    85.0
1    90.0
2    95.0
Name: Score, dtype: float64


In [12]:
# Advanced: Reading/writing CSV
df.to_csv('sample.csv', index=False)
loaded = pd.read_csv('sample.csv')
print("Loaded from CSV:\n", loaded)


Loaded from CSV:
       Name  Age  Score  Passed
0    Alice   25   85.0   False
1      Bob   30    NaN   False
2  Charlie   35   95.0    True
